services:
  db:
    image: postgres
    container_name: locadora-db
    environment:
      POSTGRES_DB: locadora-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - locadora_data:/var/lib/postgresql
volumes:
  locadora_data: